config/routes.rb
Rails.application.routes.draw do

  root to: 'contacts#index'

  resources :contacts do
    resources :phones, except: [:show]
  end

  resources :phones, except: [:show]

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :presence => true
  has_many :phones

end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact

  validates :number, :presence => true
  validates :contact_id, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
    @contact = Contact.new
    # render('contacts/index.html.erb')
  end


  def new
    @contact = Contact.new
    # render('contacts/new.html.erb')
  end


  def create
    @contact = Contact.new(params[:contact])
    if @contact.save
      flash[:notice] = "Your contact was added to Wikipages!"
      # redirect_to("/contacts/#{@contact.id}")
      redirect_to contacts_path(@contact)
    else
      # render('contacts/new.html.erb')
      render 'new'
    end
  end


  def show
    @contact = Contact.find(params[:id])
    # render('contacts/show.html.erb')
  end



  def edit
    @contact = Contact.find(params[:id])
    # render('contacts/edit.html.erb')
  end


  def update
    @contact = Contact.find(params[:id])
    if @contact.update(params[:contact])
      flash[:notice] = "Your contact was updated!"
      # redirect_to("/contacts/#{@contact.id}")
      redirect_to contact_path(@contact)
    else
      # render('contacts/edit.html.erb')
      render 'edit'
    end
  end


  def destroy
    @contact = Contact.find(params[:id])
    if @contact.destroy
      flash[:notice] = "Your contact was deleted!"
      redirect_to '/contacts'
    else
      redirect_to :back
    end
  end


end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  def new
    @contact = Contact.find(params[:contact_id])
    @phone = @contact.phones.build

    # contact = Contact.find(params[:contact_id])
    # @phone = contact.phones.new
    # render('phones/new.html.erb')
  end


  def create
    @contact = Contact.find params[:contact_id]
    @phone = @contact.phones.build(params[:phone])
    if @phone.save
      # render('phones/success.html.erb')
      render 'success'
    else
      # render('phones/new.html.erb')
      render 'new'
    end
  end


  def edit
    @phone = Phone.find(params[:id])
    # render('phones/edit.html.erb')
  end


  def update
    @phone = Phone.find(params[:id])
    if @phone.update(params[:phone])
      # render('phones/success.html.erb')
      render 'success'
    else
      # render('phones/edit.html.erb')
      render 'edit'
    end
  end

  def destroy
    @phone = Phone.find(params[:id])
    @phone.destroy
    # render ('phones/destroy.html.erb')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form try.html.erb
<!--<%= #form_for(@contact) do |f| %>-->
<!--<div class="form-group">-->
<!--<%= #f.label :name %>-->
<!--<%= #f.text_field :name %>-->
<!--</div>-->
<!--<div class="form-group">-->
<!--<%= #f.label :phone %>-->
<!--<%= #f.text_field :phone %>-->
<!--</div>-->
<!--<div class="form-group">-->
<!--<%= #f.label :email %>-->
<!--<%= #f.text_field :email %>-->
<!--</div>-->
<!--<%= #f.submit(class: "btn btn-primary")%>-->
<!--<% #end %>-->

app/views/contacts/_form.html.erb
<%= render('layouts/errors', :object => @contact) %>


<label for="contact_name">Name</label>
<input id="contact_name" name="contact[name]" type="text" value="<%= @contact.name %>">
<label for="contact_phone">Phone</label>
<input id="contact_phone" name="contact[phone]" type="text" value="<%= @contact.phone %>">
<label for="contact_email">Email</label>
<input id="contact_email" name="contact[email]" type="text" value="<%= @contact.email %>">

app/views/contacts/destroy.html.erb
<h1>Contact deleted</h1>
<!--<p>Would you like to <a href="/contacts">see all the contacts</a>, or <a href="/contacts/new">create a new one</a>?</p>-->

<p>Would you like to <%= link_to "see all the contacts", contacts_path %>, or <%= link_to "create a new one", new_contact_path %></p>

app/views/contacts/edit.html.erb
<% content_for(:title, "Edit contact | Wikipages") %>

<h1>Edit contact</h1>

<form action="/contacts/<%= @contact.id %>" method="post">
  <input name="_method" type="hidden" value="patch">

<%= render('form') %>

<button>Update contact</button>

</form>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<ul>
  <% @contacts.each do |contact| %>
  <li><a href="/contacts/<%= contact.id %>"><%= contact.name %></a></li>
  <% end %>
</ul>

<h2>New contact</h2>

<form action="/contacts/<%= @contact.id %>" method="post">
<%= render('form') %>
<button>Create contact</button>
</form>

app/views/contacts/new.html.erb
<% content_for(:title, "New contact | Wikipages") %>

<h1>New contact</h1>

<form action="/contacts/<%= @contact.id %>" method="post">

<%= render('form') %>

<button>Create contact</button>

</form>

app/views/contacts/show.html.erb
<% content_for(:title, 'New contact | Wikipages') %>

<!--<h1>New contact</h1>-->

<h1><%= @contact.name %></h1>

<p>Phone: <%= @contact.phone %></p>
<p>Email: <%= @contact.email %><p>


<p>Phones:</p>
<ul>
  <% @contact.phones.each do |phone| %>
      <li>
        <%= phone.number %>
        <!--<a href="/contacts/<%= @contact.id %>/phones/<%= phone.id %>/edit">Edit</a> -->
        <%= link_to "Edit", edit_phone_path(phone) %> |
        <a href="/contacts/<%= @contact.id %>/phones/<%= phone.id %>"
           data-confirm="You sure?"
           data-method="delete"
           rel="nofollow">Delete</a>

      </li>
  <% end %>
</ul>

<p><a href="/contacts/<%= @contact.id %>/phones/new">Add phone</a></p>
<!--<%= link_to "Add phone", phone_path(@contact) %>-->

<p><a href="/contacts/<%= @contact.id %>/edit">Edit</a></p>

<p><a href="/contacts/<%= @contact.id %>"
      data-confirm="You sure?"
      data-method="delete"
      rel="nofollow">Delete</a></p>

<p><a href="/contacts">Return to contact listing</a></p>

app/views/contacts/success.html.erb
<h1>Contact saved!</h1>
<p>Your contact was successfully saved.</p>
<p><a href="/contacts/<%= @contact.id %>">View <%= @contact.name %></a></p>
<p><a href="/contacts">Return to contact listing</a></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li> <%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikipages</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:alert] %>
<%= flash[:notice] %>

<%= yield %>

<title><%= yield(:title) %></title>

</body>
</html>

app/views/phones/_form.html.erb
<label for="phone_number">Number</label>
<input id="phone_number" name="phone[number]" type="text" value="<%= @phone.number %>">

app/views/phones/destroy.html.erb
<h1>Phone deleted</h1>
<!--<p>Would you like to <a href="/phones">see all the phones</a>, or <a href="/phones/new">create a new one</a>?</p>-->

app/views/phones/edit.html.erb
<h1>Edit phone</h1>

<%= render('layouts/errors', :object => @phone) %>

<form action="/contacts/:contact_id/phones/<%= @phone.id %>" method="post">
  <input name="_method" type="hidden" value="patch">
  <%= render('form') %>
  <button>Update contact</button>

</form>


<!--contacts/:contact_id/phones/:id/edit-->

app/views/phones/new.html.erb
<h1>New phone number for <%= @phone.contact.name %></h1>

<%= render('layouts/errors', :object => @phone) %>

<form action="/contacts/<%= @contact.id %>/phones" method="post">
  <%= render('form') %>
  <button>Add phone</button>
</form>


<!--contacts/:contact_id/phones/new-->

app/views/phones/success.html.erb
<h1>Phone number saved!</h1>
<p>Your phone number was successfully saved.</p>
<p><a href="/contacts/<%= @phone.contact_id %>">View <%= @phone.number %></a></p>
<p><a href="/contacts">Return to contact listing</a></p>